### ISSUE TITLE
Switching a resource_reference from type to child_type can be backwards compat

### ISSUE THREAD

**Issue by noahdietz** [googleapis/proto-breaking-change-detector#153]
Switching a `resource_reference` annotation from a specific `type` reference to a `child_type` reference that includes the original `type` as a parent pattern should be backwards compatible, if the order of the patterns does not change. For example:

**Original**
```
string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      type: "cloudresourcemanager.googleapis.com/Organization"
    }
];
```

**New**
```
string parent = 1 [
    (google.api.field_behavior) = REQUIRED,
    (google.api.resource_reference) = {
      child_type: "myapi.googleapis.com/MyResource"
    }
];
```

where 
```
option (google.api.resource) = {
    type: "myapi.googleapis.com/MyResource"
    pattern: "organizations/{organization}/myresources/{myresource}"
    pattern: "folders/{folder}/myresources/{myresource}"
    pattern: "projects/{project}/myresources/{myresource}"
  };
```

Because `Organization` is still a parent pattern (and it is still the first), this should be backwards compat.

**Comment by xiaozhenliu-gg5** [comment]
This is because the presubmit BCD is not compiling proto files with "common_resources.proto", when BCD cannot find the resource definition, it takes as child_type <-> type conversion not compatible. Resolved this from presubmit BCD, so close this issue. Thanks.
