### ISSUE TITLE
Mark fields entering or exiting a oneof as an error

### ISSUE THREAD

**Issue by software-dov** [googleapis/proto-breaking-change-detector#169]
Consider the following proto message definition for a hypothetical API:
```proto
message MolluscRequest {
    string squid_taxonomy = 1;
    string octopus_taxonomy = 2;        
}
```
Now imagine that the API protos are updated to the following:
```proto
message MolluscRequest {
    oneof taxonomy {
        string squid_taxonomy = 1;
        string octopus_taxonomy = 2;        
    }
}
```

Although it may not be intuitively obvious, this is a breaking change.
```go
// Go application
molluscReq := MolluscRequest{SquidTaxonomy: Proto.String("Architeuthis dux"), OctopusTaxonomy: Proto.String("Octopus vulgaris"),}
molluscRsp := client.GetMollusc(ctx, molluscReq)
```

The serialized representation of `molluscReq` changes between the two API versions, which may affect the server semantics.

The reverse, moving fields out of a `oneof`, is clearly a breaking change as well.

This is a feature tracking issue to detect and issue an error if a field moves into or out of a `oneof` declaration.

**Comment by alexander-fenster** [comment]
I believe this is currently handled as a breaking change.  At least we have the corresponding messages:

https://github.com/googleapis/proto-breaking-change-detector/blob/62712fef97fcc502875eb3aa9e034b28b4ef4dcc/src/findings/messages.py#L47-L52

If it does not work, please reopen.
