### ISSUE TITLE
support aliases in enums

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/proto-breaking-change-detector#205]
Enum values can be aliased:

```
enum E {
  option allow_alias = true;

  KEY = 1;
  ANOTHER_KEY = 1;
}
```

Adding the alias is currently considered a breaking change because the BCD does not know about this possibility.

**Comment by alexander-fenster** [comment]
@tmatsuo I'll update this from "p3 feature request" to "p2 bug" because I'm seeing more usage of enum aliases, all of them are reported as breaking changes.

**Comment by tmatsuo** [comment]
https://github.com/googleapis/proto-breaking-change-detector/blob/c537056cb329e618071ba369406e1a518581c7b4/src/proto_bcd/comparator/wrappers.py#L126

The internal wrapper has a wrong assumption that the number is unique.
