### ISSUE TITLE
moving messages between files must be considered breaking

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/proto-breaking-change-detector#233]
Moving messages between files is breaking for the code in most languages since imports / includes must be changed. Currently, BCD does not detect this kind of change at all.

**Comment by parthea** [comment]
Could this be bumped from `p3` to `p2`? In Python Cloud SDK, we recently had a breaking change slip through:
https://github.com/googleapis/google-cloud-python/pull/11555#discussion_r1289982070

**Comment by dazuma** [comment]
Just happened again in cl/557476391 (Ruby PR: https://github.com/googleapis/google-cloud-ruby/pull/22793). This type of change directly violates [AIP-180](https://google.aip.dev/180#moving-components-between-files) and I think we should flag it.
